# Generated by Django 3.1.7 on 2021-04-21 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=9)),
                ('city', models.ImageField(max_length=30, upload_to='')),
                ('streetAddress', models.ImageField(max_length=50, upload_to='')),
                ('postalCode', models.ImageField(max_length=20, upload_to='')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoryID',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(default='card', max_length=60),
        ),
        migrations.CreateModel(
            name='VinNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('pointID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.szikpoint')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
    ]
