# Generated by Django 3.2 on 2021-04-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_invoice_invoicefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fileName',
        ),
    ]
