# Generated by Django 3.2 on 2021-04-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210424_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szikpoint',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='szikpoint',
            name='postalCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='szikpoint',
            name='streetAddress',
            field=models.CharField(max_length=50),
        ),
    ]
