# Generated by Django 3.2 on 2021-05-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_invoice_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.usertype'),
        ),
    ]
