# Generated by Django 3.1.7 on 2021-04-19 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
