# Generated by Django 3.2 on 2021-05-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_orderline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='szikpoint',
            name='mapLatitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='szikpoint',
            name='mapLongitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
