# Generated by Django 3.2.2 on 2021-05-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210511_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='orderID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='pdfFile',
            new_name='pdf_file',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderDate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoryID',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discountPrice',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='productquantity',
            old_name='pointID',
            new_name='point_id',
        ),
        migrations.RenameField(
            model_name='productquantity',
            old_name='productID',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='szikpoint',
            old_name='mapLatitude',
            new_name='map_latitude',
        ),
        migrations.RenameField(
            model_name='szikpoint',
            old_name='mapLongitude',
            new_name='map_longitude',
        ),
        migrations.RenameField(
            model_name='szikpoint',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='szikpoint',
            old_name='streetAddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='streetAddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userType',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='vinnumber',
            old_name='userID',
            new_name='user_id',
        ),
    ]
