# Generated by Django 3.2.2 on 2021-06-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discount',
        ),
    ]
