# Generated by Django 3.2.2 on 2021-06-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_checkoutaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
