# Generated by Django 3.2.4 on 2021-06-18 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0013_rename_zip_checkoutaddress_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Pozycja na zamówieniu', 'verbose_name_plural': 'Pozycje na zamówieniu'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='szikpoint',
            options={'verbose_name': 'Punkt SZiK', 'verbose_name_plural': 'Punkty SZiK'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'Typ użytkownika', 'verbose_name_plural': 'Typy użytkowników'},
        ),
        migrations.AlterModelOptions(
            name='vinnumber',
            options={'verbose_name': 'Numer VIN', 'verbose_name_plural': 'Numery VIN'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=9, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('street_address', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.usertype')),
            ],
        ),
        migrations.AlterField(
            model_name='vinnumber',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
