# Generated by Django 3.2.4 on 2021-06-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210618_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='pages.InvoiceFile/bytes/filename/mimetype'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
