# Generated by Django 3.2.4 on 2021-06-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210618_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='ordered',
        ),
    ]
